services:
  web:
    build: ./backend
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    expose:
      - "8000"
    env_file:
      - ./backend/.env
    environment:
      - DEBUG=True

  nginx:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: nginx_proxy
    ports:
      - "8000:8000"
    depends_on:
      - web
