# Generated by Django 6.0.5 on 2026-09-26 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='waste_reason',
            field=models.CharField(blank=True, choices=[('spolied', 'خراب شده'), ('expired', 'تاریخ گذشته'), ('damaged', 'آسیب دیده'), ('other', 'سایر')], default='', max_length=20, verbose_name='دلیل ضایعات'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='minimum_stock',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='حداقل موجودی'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='target_stock',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='موجودی هدف'),
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='نام انبار')),
                ('warehouse_type', models.CharField(choices=[('mother', 'انبار مرکزی'), ('kitchen', 'آشپزخانه'), ('cold_storage', 'سردخانه'), ('freezer', 'فریزر'), ('vegetables', 'انبار سبزیجات'), ('branch', 'شعبه'), ('other', 'سایر')], db_index=True, default='other', max_length=20, verbose_name='نوع انبار')),
                ('is_mother', models.BooleanField(default=False, help_text='هر رستوران فقط یک انبار مرکزی می\u200cتواند داشته باشد', verbose_name='انبار مرکزی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='restaurant.restaurant', verbose_name='رستوران')),
            ],
            options={
                'verbose_name': 'انبار',
                'verbose_name_plural': 'انبارها',
                'ordering': ['-is_mother', 'name'],
                'unique_together': {('restaurant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Receiving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('received', 'دریافت شده'), ('partial', 'دریافت جزئی')], db_index=True, default='received', max_length=20, verbose_name='وضعیت')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تحویل')),
                ('purchase_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receivings', to='restaurant.purchaseinvoice', verbose_name='فاکتور خرید')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receivings', to=settings.AUTH_USER_MODEL, verbose_name='تحویل\u200cگیرنده')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='restaurant.restaurant', verbose_name='رستوران')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receivings', to='restaurant.supplier', verbose_name='تأمین\u200cکننده')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivings', to='restaurant.warehouse', verbose_name='انبار مقصد')),
            ],
            options={
                'verbose_name': 'تحویل بار',
                'verbose_name_plural': 'تحویل\u200cهای بار',
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='restaurant.warehouse', verbose_name='انبار'),
        ),
        migrations.CreateModel(
            name='PurchaseListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='مقدار پیشنهادی')),
                ('status', models.CharField(choices=[('need', 'نیاز به خرید'), ('purchasing', 'در حال خرید'), ('purchased', 'خرید انجام شد'), ('received', 'وارد انبار شد')], db_index=True, default='need', max_length=20, verbose_name='وضعیت')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('purchase_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_list_items', to='restaurant.purchaseinvoice', verbose_name='فاکتور خرید')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_list_items', to='restaurant.rawmaterial', verbose_name='ماده اولیه')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='restaurant.restaurant', verbose_name='رستوران')),
            ],
            options={
                'verbose_name': 'آیتم لیست خرید',
                'verbose_name_plural': 'آیتم\u200cهای لیست خرید',
                'ordering': ['status', 'created_at'],
                'indexes': [models.Index(fields=['restaurant', 'status'], name='restaurant__restaur_1df60d_idx')],
                'unique_together': {('restaurant', 'raw_material')},
            },
        ),
        migrations.CreateModel(
            name='ReceivingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='مقدار سفارش\u200cداده\u200cشده')),
                ('quantity_received', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='مقدار دریافت\u200cشده')),
                ('unit', models.CharField(choices=[('kg', 'کیلوگرم'), ('g', 'گرم'), ('l', 'لیتر'), ('ml', 'میلی\u200cلیتر'), ('unit', 'عدد'), ('bunch', 'دسته'), ('pack', 'بسته')], max_length=10, verbose_name='واحد')),
                ('unit_price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت واحد')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receiving_items', to='restaurant.rawmaterial', verbose_name='ماده اولیه')),
                ('receiving', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='restaurant.receiving', verbose_name='تحویل')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='restaurant.restaurant', verbose_name='رستوران')),
            ],
            options={
                'verbose_name': 'آیتم تحویل',
                'verbose_name_plural': 'آیتم\u200cهای تحویل',
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity_received__gte', 0)), name='rms_recvitem_qty_gte_0'), models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='rms_recvitem_price_gte_0')],
            },
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='مقدار')),
                ('unit', models.CharField(choices=[('kg', 'کیلوگرم'), ('g', 'گرم'), ('l', 'لیتر'), ('ml', 'میلی\u200cلیتر'), ('unit', 'عدد'), ('bunch', 'دسته'), ('pack', 'بسته')], max_length=10, verbose_name='واحد')),
                ('status', models.CharField(choices=[('completed', 'انجام شده'), ('cancelled', 'لغو شده')], db_index=True, default='completed', max_length=20, verbose_name='وضعیت')),
                ('reference', models.CharField(blank=True, max_length=200, verbose_name='مرجع')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انجام')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transfers', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='restaurant.rawmaterial', verbose_name='ماده اولیه')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='restaurant.restaurant', verbose_name='رستوران')),
                ('destination_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='restaurant.warehouse', verbose_name='انبار مقصد')),
                ('source_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='restaurant.warehouse', verbose_name='انبار مبدأ')),
            ],
            options={
                'verbose_name': 'انتقال کالا',
                'verbose_name_plural': 'انتقال\u200cهای کالا',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['restaurant', '-created_at'], name='restaurant__restaur_9d9a0d_idx'), models.Index(fields=['restaurant', 'source_warehouse', '-created_at'], name='restaurant__restaur_6f48fd_idx'), models.Index(fields=['restaurant', 'destination_warehouse', '-created_at'], name='restaurant__restaur_2e4fad_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='rms_transfer_qty_gt_0')],
            },
        ),
        migrations.CreateModel(
            name='StockLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_original', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='مقدار اولیه')),
                ('quantity_remaining', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='مقدار باقیمانده')),
                ('unit_cost', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت واحد')),
                ('reference_type', models.CharField(blank=True, default='', max_length=50, verbose_name='نوع مرجع')),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='شناسه مرجع')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ورود')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_layers', to='restaurant.rawmaterial', verbose_name='ماده اولیه')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='restaurant.restaurant', verbose_name='رستوران')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_layers', to='restaurant.supplier', verbose_name='تأمین\u200cکننده')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_layers', to='restaurant.warehouse', verbose_name='انبار')),
            ],
            options={
                'verbose_name': 'لایه قیمت',
                'verbose_name_plural': 'لایه\u200cهای قیمت',
                'ordering': ['received_at'],
                'indexes': [models.Index(fields=['restaurant', 'raw_material', 'warehouse'], name='restaurant__restaur_6e60eb_idx'), models.Index(fields=['restaurant', 'raw_material', 'received_at'], name='restaurant__restaur_13e9be_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='موجودی')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='restaurant.rawmaterial', verbose_name='ماده اولیه')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='restaurant.restaurant', verbose_name='رستوران')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='restaurant.warehouse', verbose_name='انبار')),
            ],
            options={
                'verbose_name': 'موجودی انبار',
                'verbose_name_plural': 'موجودی\u200cهای انبار',
                'indexes': [models.Index(fields=['restaurant', 'warehouse', 'raw_material'], name='restaurant__restaur_4bb714_idx'), models.Index(fields=['restaurant', 'raw_material'], name='restaurant__restaur_458722_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='rms_stockitem_qty_gte_0')],
                'unique_together': {('restaurant', 'warehouse', 'raw_material')},
            },
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='موجودی قبل')),
                ('new_quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='موجودی جدید')),
                ('difference', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='اختلاف')),
                ('adjustment_type', models.CharField(choices=[('count', 'شمارش موجودی'), ('correction', 'اصلاح'), ('damage', 'آسیب دیدگی'), ('other', 'سایر')], default='count', max_length=20, verbose_name='نوع اصلاح')),
                ('reason', models.CharField(blank=True, max_length=500, verbose_name='دلیل')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('adjusted_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ اصلاح')),
                ('adjusted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_adjustments', to=settings.AUTH_USER_MODEL, verbose_name='انجام\u200cدهنده')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='restaurant.rawmaterial', verbose_name='ماده اولیه')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='restaurant.restaurant', verbose_name='رستوران')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='restaurant.warehouse', verbose_name='انبار')),
            ],
            options={
                'verbose_name': 'اصلاح موجودی',
                'verbose_name_plural': 'اصلاحات موجودی',
                'ordering': ['-adjusted_at'],
                'indexes': [models.Index(fields=['restaurant', '-adjusted_at'], name='restaurant__restaur_f3b1f7_idx'), models.Index(fields=['restaurant', 'raw_material', '-adjusted_at'], name='restaurant__restaur_f9381e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='receiving',
            index=models.Index(fields=['restaurant', '-received_at'], name='restaurant__restaur_024b05_idx'),
        ),
        migrations.AddIndex(
            model_name='receiving',
            index=models.Index(fields=['restaurant', 'warehouse', '-received_at'], name='restaurant__restaur_d433a5_idx'),
        ),
    ]
