# Generated by Django 6.0.5 on 2026-08-23 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionarygroup',
            name='usage_invoice',
            field=models.BooleanField(default=True, verbose_name='فاکتور خرید'),
        ),
        migrations.AlterField(
            model_name='dictionarygroup',
            name='usage_kitchen',
            field=models.BooleanField(default=True, verbose_name='آشپزخانه'),
        ),
        migrations.AlterField(
            model_name='dictionarygroup',
            name='usage_pos',
            field=models.BooleanField(default=True, verbose_name='POS'),
        ),
        migrations.AlterField(
            model_name='dictionarygroup',
            name='usage_recipes',
            field=models.BooleanField(default=True, verbose_name='رسپی'),
        ),
        migrations.AlterField(
            model_name='dictionarygroup',
            name='usage_warehouse',
            field=models.BooleanField(default=True, verbose_name='انبار'),
        ),
    ]
