# Generated by Django 6.0.5 on 2026-09-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='نام انگلیسی'),
        ),
        migrations.AddField(
            model_name='food',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='نام انگلیسی'),
        ),
    ]
