# Generated by Django 6.0.5 on 2026-09-13 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_category_name_en_food_name_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_dictionary', models.BooleanField(default=True, help_text='فعال = غذاها از لیست غذاها (Food) خوانده میشه با تصویر، قیمت و موجودی. غیرفعال = صندوقدار دستی اسم و قیمت وارد میکنه.', verbose_name='استفاده از دیکشنری غذا')),
                ('allow_price_edit', models.BooleanField(default=False, help_text='صندوق\u200cدار بتونه قیمت غذا رو از صندوق تغییر بده.', verbose_name='اجازه تغییر قیمت توسط صندوقدار')),
                ('show_stock', models.BooleanField(default=True, verbose_name='نمایش موجودی روی کارت غذا')),
                ('default_payment', models.CharField(choices=[('cash', 'نقدی'), ('card', 'کارتخوان'), ('online', 'آنلاین')], default='cash', max_length=20, verbose_name='روش پرداخت پیش\u200cفرض')),
                ('require_customer', models.BooleanField(default=False, help_text='اگر فعال باشه، بدون ثبت نام مشتری نمیشه سفارش ثبت کرد.', verbose_name='اجبار ثبت اطلاعات مشتری')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='restaurant.restaurant', verbose_name='رستوران')),
            ],
            options={
                'verbose_name': 'تنظیمات صندوق فروش',
                'verbose_name_plural': 'تنظیمات صندوق فروش',
            },
        ),
    ]
