# Generated by Django 6.0.5 on 2026-08-25 08:46

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_dictionarygroup_usage_invoice_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='order',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='tenantservice',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ و ساعت پایان'),
        ),
        migrations.AlterField(
            model_name='tenantservice',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ و ساعت شروع'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره موبایل'),
        ),
    ]
