# Generated by Django 6.0.5 on 2026-09-20 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_possettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardTerminalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='کارت\u200cخوان', max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('port', models.PositiveIntegerField(default=8080)),
                ('protocol', models.CharField(choices=[('http', 'HTTP'), ('https', 'HTTPS')], default='http', max_length=10)),
                ('terminal_id', models.CharField(blank=True, max_length=100)),
                ('merchant_id', models.CharField(blank=True, max_length=100)),
                ('api_path', models.CharField(default='/api/v1/pay', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_terminals', to='restaurant.tenant')),
            ],
            options={
                'verbose_name': 'دستگاه کارت\u200cخوان',
                'verbose_name_plural': 'دستگاه\u200cهای کارت\u200cخوان',
            },
        ),
        migrations.CreateModel(
            name='PaymentGatewayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_type', models.CharField(choices=[('zarinpal', 'زرین\u200cپال'), ('saman', 'سامان'), ('parsian', 'پارسیان'), ('mellat', 'ملت'), ('custom', 'سفارشی')], default='zarinpal', max_length=20)),
                ('title', models.CharField(default='درگاه پرداخت', max_length=100)),
                ('merchant_id', models.CharField(max_length=200)),
                ('api_key', models.CharField(blank=True, max_length=500)),
                ('callback_url', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('is_sandbox', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_gateways', to='restaurant.tenant')),
            ],
            options={
                'verbose_name': 'درگاه پرداخت',
                'verbose_name_plural': 'درگاه\u200cهای پرداخت',
                'unique_together': {('tenant', 'gateway_type')},
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('cash', 'نقدی'), ('card_reader', 'کارت\u200cخوان'), ('online', 'آنلاین')], max_length=20)),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('processing', 'در حال پردازش'), ('success', 'موفق'), ('failed', 'ناموفق'), ('cancelled', 'لغو شده')], default='pending', max_length=20)),
                ('rrn', models.CharField(blank=True, max_length=50)),
                ('card_last_four', models.CharField(blank=True, max_length=4)),
                ('trace_number', models.CharField(blank=True, max_length=50)),
                ('authority', models.CharField(blank=True, max_length=200)),
                ('ref_id', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('gateway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.paymentgatewayconfig')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='restaurant.order')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='restaurant.tenant')),
                ('terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.cardterminalconfig')),
            ],
            options={
                'verbose_name': 'تراکنش پرداخت',
                'verbose_name_plural': 'تراکنش\u200cهای پرداخت',
                'ordering': ['-created_at'],
            },
        ),
    ]
