# Generated by Django 6.0.5 on 2026-09-21 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_cardterminalconfig_paymentgatewayconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='موجودی'),
        ),
    ]
