# Generated by Django 6.0.5 on 2026-09-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_food_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='discount',
            field=models.PositiveIntegerField(default=0, verbose_name='تخفیف دسته\u200cبندی'),
        ),
        migrations.AddField(
            model_name='category',
            name='discount_type',
            field=models.CharField(choices=[('fixed', 'مبلغ ثابت'), ('percent', 'درصدی')], default='fixed', max_length=10, verbose_name='نوع تخفیف'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name_en',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_name_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='نام انگلیسی آیتم'),
        ),
    ]
