# Generated by Django 6.0.5 on 2026-06-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_add_category_to_invoice_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semifinished',
            name='category',
            field=models.CharField(choices=[('sauce', 'سس\u200cها'), ('dough', 'خمیرها'), ('marinade', 'مارینادها'), ('soup', 'سوپ\u200cها'), ('syrup', 'شربت\u200cها'), ('other', 'سایر')], default='other', max_length=20, verbose_name='دسته\u200cبندی'),
        ),
    ]
