# Generated by Django 6.0.5 on 2026-06-21 08:04

import restaurant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_daycloselog_dayclosereport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daycloselog',
            name='details',
            field=models.JSONField(default=dict, encoder=restaurant.models.DecimalSafeEncoder, verbose_name='جزئیات'),
        ),
        migrations.AlterField(
            model_name='dayclosereport',
            name='discount_total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='کل تخفیف'),
        ),
        migrations.AlterField(
            model_name='dayclosereport',
            name='inventory_snapshot',
            field=models.JSONField(default=dict, encoder=restaurant.models.DecimalSafeEncoder, verbose_name='عکس موجودی'),
        ),
        migrations.AlterField(
            model_name='dayclosereport',
            name='items_detail',
            field=models.JSONField(default=list, encoder=restaurant.models.DecimalSafeEncoder, verbose_name='جزئیات آیتم\u200cها'),
        ),
        migrations.AlterField(
            model_name='dayclosereport',
            name='top_items',
            field=models.JSONField(default=list, encoder=restaurant.models.DecimalSafeEncoder, verbose_name='پرفروش\u200cترین\u200cها'),
        ),
        migrations.AlterField(
            model_name='dayclosereport',
            name='total_cost',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='هزینه کل'),
        ),
        migrations.AlterField(
            model_name='dayclosereport',
            name='total_profit',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='سود خالص'),
        ),
        migrations.AlterField(
            model_name='dayclosereport',
            name='total_sales',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='فروش کل'),
        ),
        migrations.AlterField(
            model_name='dayclosereport',
            name='waste_value',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='ارزش ضایعات'),
        ),
        migrations.AlterField(
            model_name='productionlog',
            name='materials_consumed',
            field=models.JSONField(blank=True, default=list, encoder=restaurant.models.DecimalSafeEncoder, verbose_name='مواد مصرفی'),
        ),
    ]
