# Generated by Django 6.0.5 on 2026-07-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_alter_kitcheninventory_options_user_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='تأیید مدیر'),
        ),
    ]
