# Generated by Django 6.0.5 on 2026-07-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0017_alter_dayclosereport_discount_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت (تومان)'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت (تومان)'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='quantity',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='readymaterial',
            name='purchase_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت خرید (تومان)'),
        ),
        migrations.AlterField(
            model_name='readymaterial',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='readymaterial',
            name='selling_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت فروش (تومان)'),
        ),
        migrations.AlterField(
            model_name='semifinished',
            name='quantity_produced',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مقدار تولید شده'),
        ),
        migrations.AlterField(
            model_name='semifinishedingredient',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مقدار مصرفی'),
        ),
    ]
