# Generated by Django 6.0.5 on 2026-07-27 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0019_service_itemdictionary_dict_category_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='total_packaging_cost',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='هزینه بسته\u200cبندی'),
        ),
        migrations.CreateModel(
            name='RecipePackagingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='مقدار')),
                ('unit', models.CharField(choices=[('kg', 'کیلوگرم'), ('g', 'گرم'), ('l', 'لیتر'), ('ml', 'میلی\u200cلیتر'), ('unit', 'عدد'), ('bunch', 'دسته'), ('pack', 'بسته')], default='unit', max_length=10, verbose_name='واحد')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packaging_usages', to='restaurant.rawmaterial', verbose_name='ماده بسته\u200cبندی')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packaging_items', to='restaurant.recipe', verbose_name='دستور پخت')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='restaurant.restaurant', verbose_name='رستوران')),
            ],
            options={
                'verbose_name': 'آیتم بسته\u200cبندی رسپی',
                'verbose_name_plural': 'آیتم\u200cهای بسته\u200cبندی رسپی',
                'unique_together': {('recipe', 'raw_material')},
            },
        ),
    ]
