# Generated by Django 6.0.5 on 2026-07-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0020_recipe_total_packaging_cost_recipepackagingitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='material_type',
            field=models.CharField(choices=[('raw', 'ماده اولیه'), ('packaging', 'بسته\u200cبندی و جعبه')], db_index=True, default='raw', max_length=20, verbose_name='نوع ماده'),
        ),
    ]
