# Generated by Django 6.0.5 on 2026-07-27 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0021_rawmaterial_material_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagingMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('unit', models.CharField(choices=[('unit', 'عدد'), ('pack', 'بسته'), ('roll', 'رول'), ('sheet', 'شیت'), ('box', 'جعبه'), ('bag', 'کیسه'), ('cup', 'لیوان'), ('lid', 'درب'), ('container', 'ظرف')], default='unit', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, help_text='موجودی انبار', max_digits=12)),
                ('price', models.DecimalField(decimal_places=0, default=0, help_text='قیمت هر واحد (تومان)', max_digits=12)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packaging_materials', to='restaurant.restaurant')),
            ],
            options={
                'verbose_name': 'ماده بسته\u200cبندی',
                'verbose_name_plural': 'مواد بسته\u200cبندی',
                'ordering': ['name'],
            },
        ),
    ]
