# Generated by Django 6.0.5 on 2026-07-27 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0022_packagingmaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdictionary',
            name='material_type',
            field=models.CharField(choices=[('raw', 'ماده اولیه'), ('packaging', 'بسته\u200cبندی')], default='raw', max_length=20, verbose_name='نوع ماده'),
        ),
    ]
