# Generated by Django 6.0.5 on 2026-07-28 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0023_itemdictionary_material_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='raw_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='restaurant.rawmaterial', verbose_name='ماده اولیه انبار'),
        ),
    ]
