# Generated by Django 6.0.5 on 2026-07-29 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0024_purchaseinvoiceitem_raw_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdictionary',
            name='category',
            field=models.CharField(blank=True, choices=[('raw_material', 'ماده اولیه'), ('semi_finished', 'نیمه\u200cآماده'), ('ready_material', 'ماده آماده'), ('final_product', 'محصول نهایی')], db_index=True, default='', max_length=20, verbose_name='دسته\u200cبندی'),
        ),
        migrations.CreateModel(
            name='DictionaryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='نام گروه')),
                ('slug', models.CharField(max_length=50, verbose_name='شناسه انگلیسی')),
                ('icon', models.CharField(default='bi-archive', max_length=30, verbose_name='آیکون')),
                ('color', models.CharField(default='#6b7280', max_length=7, verbose_name='رنگ (hex)')),
                ('sort_order', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('usage_recipes', models.BooleanField(default=False, verbose_name='رسپی')),
                ('usage_warehouse', models.BooleanField(default=False, verbose_name='انبار')),
                ('usage_pos', models.BooleanField(default=False, verbose_name='POS')),
                ('usage_invoice', models.BooleanField(default=False, verbose_name='فاکتور خرید')),
                ('usage_kitchen', models.BooleanField(default=False, verbose_name='آشپزخانه')),
                ('is_system', models.BooleanField(default=False, verbose_name='سیستمی (غیرقابل حذف)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='restaurant.restaurant', verbose_name='رستوران')),
            ],
            options={
                'verbose_name': 'گروه دیکشنری',
                'verbose_name_plural': 'گروه\u200cهای دیکشنری',
                'ordering': ['sort_order', 'name'],
                'unique_together': {('restaurant', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='itemdictionary',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='restaurant.dictionarygroup', verbose_name='گروه'),
        ),
    ]
