# Generated by Django 6.0.5 on 2026-08-02 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0025_alter_itemdictionary_category_dictionarygroup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capacityanalysis',
            name='kitchen_product',
        ),
        migrations.RemoveField(
            model_name='capacityanalysis',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='kitchendiscount',
            name='kitchen_product',
        ),
        migrations.RemoveField(
            model_name='kitchendiscount',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='packagingmaterial',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='kitchenproduct',
            name='min_stock',
            field=models.PositiveIntegerField(default=0, help_text='صفر = بدون محدودیت. کمتر از این مقدار = ارور در سیستم', verbose_name='حداقل موجودی'),
        ),
        migrations.AddField(
            model_name='wastelog',
            name='cost_per_unit',
            field=models.PositiveIntegerField(default=0, help_text='خودکار از هزینه تولید محصول پر می\u200cشود', verbose_name='هزینه هر واحد (تومان)'),
        ),
        migrations.AddField(
            model_name='wastelog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده'),
        ),
        migrations.AddField(
            model_name='wastelog',
            name='notes',
            field=models.TextField(blank=True, verbose_name='یادداشت'),
        ),
        migrations.AlterField(
            model_name='kitcheninventory',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=5, verbose_name='آستانه کمبود (سیستمی)'),
        ),
        migrations.AlterField(
            model_name='recipepackagingitem',
            name='raw_material',
            field=models.ForeignKey(limit_choices_to={'material_type': 'packaging'}, on_delete=django.db.models.deletion.CASCADE, related_name='packaging_usages', to='restaurant.rawmaterial', verbose_name='ماده بسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='wastelog',
            name='reason',
            field=models.CharField(choices=[('expired', 'تاریخ گذشته'), ('damaged', 'آسیب\u200cدیده'), ('overcooked', 'بیش\u200cپخت'), ('quality_issue', 'مشکل کیفیت'), ('returned', 'برگشتی مشتری'), ('other', 'سایر')], default='other', max_length=20, verbose_name='دلیل'),
        ),
        migrations.AddIndex(
            model_name='wastelog',
            index=models.Index(fields=['kitchen_product', 'reason'], name='restaurant__kitchen_57633b_idx'),
        ),
        migrations.AddIndex(
            model_name='wastelog',
            index=models.Index(fields=['-created_at'], name='restaurant__created_f703d1_idx'),
        ),
        migrations.DeleteModel(
            name='CapacityAnalysis',
        ),
        migrations.DeleteModel(
            name='KitchenDiscount',
        ),
        migrations.DeleteModel(
            name='PackagingMaterial',
        ),
    ]
