# Generated by Django 6.0.5 on 2026-08-05 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0026_remove_capacityanalysis_kitchen_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان تأیید'),
        ),
        migrations.AddField(
            model_name='order',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_orders', to=settings.AUTH_USER_MODEL, verbose_name='تأیید شده توسط'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدی'), ('card', 'کارتخوان'), ('online', 'آنلاین')], default='cash', max_length=20, verbose_name='روش پرداخت'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('failed', 'ناموفق'), ('refunded', 'بازگشت وجه')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت پرداخت'),
        ),
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('pos', 'صندوق'), ('online', 'آنلاین'), ('phone', 'تلفنی')], db_index=True, default='pos', max_length=20, verbose_name='منبع سفارش'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['source', 'status', '-created_at'], name='restaurant__source_79516d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status'], name='restaurant__payment_958ab7_idx'),
        ),
    ]
