# Generated by Django 6.0.5 on 2026-08-05 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0027_order_confirmed_at_order_confirmed_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineOrderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=True, verbose_name='سفارش آنلاین فعال')),
                ('closed_message', models.TextField(default='رستوران بسته است', verbose_name='پیام بسته بودن')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='online_settings', to='restaurant.restaurant', verbose_name='رستوران')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='آخرین تغییر توسط')),
            ],
            options={
                'verbose_name': 'تنظیمات سفارش آنلاین',
                'verbose_name_plural': 'تنظیمات سفارش آنلاین',
            },
        ),
    ]
