# Generated by Django 6.0.5 on 2026-08-06 20:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0028_onlineordersettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loyaltytransaction',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='order_id',
        ),
        migrations.AddField(
            model_name='loyaltytransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_transactions', to='restaurant.order', verbose_name='سفارش مرتبط'),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='نام آیتم'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='restaurant.supplier', verbose_name='تأمین\u200cکننده'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='restaurant.order', verbose_name='سفارش مرتبط'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='raw_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='restaurant.rawmaterial', verbose_name='ماده اولیه'),
        ),
        migrations.AlterField(
            model_name='inventoryusagelog',
            name='raw_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_logs', to='restaurant.rawmaterial', verbose_name='ماده اولیه'),
        ),
        migrations.AlterField(
            model_name='kitchenproduct',
            name='min_stock',
            field=models.PositiveIntegerField(default=0, help_text='صفر = بدون محدودیت. کمتر از این مقدار = هشدار در سیستم', verbose_name='حداقل موجودی'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='restaurant.food'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='raw_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_usages', to='restaurant.rawmaterial', verbose_name='ماده اولیه'),
        ),
        migrations.AlterField(
            model_name='recipepackagingitem',
            name='raw_material',
            field=models.ForeignKey(limit_choices_to={'material_type': 'packaging'}, on_delete=django.db.models.deletion.PROTECT, related_name='packaging_usages', to='restaurant.rawmaterial', verbose_name='ماده بسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='recipesemifinished',
            name='semi_finished',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_usages', to='restaurant.semifinished', verbose_name='ماده نیم\u200cآماده'),
        ),
        migrations.AlterField(
            model_name='semifinishedingredient',
            name='raw_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurant.rawmaterial', verbose_name='ماده اولیه'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('restaurant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='food',
            unique_together={('restaurant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='referral',
            unique_together={('restaurant', 'referrer', 'referred')},
        ),
        migrations.AlterUniqueTogether(
            name='table',
            unique_together={('restaurant', 'number')},
        ),
    ]
