# Generated by Django 6.0.5 on 2026-08-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0029_remove_loyaltytransaction_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dashboard_permissions',
            field=models.JSONField(blank=True, default=list, help_text='لیست بخش\u200cهای قابل دسترسی. خالی = پیش\u200cفرض نقش', verbose_name='دسترسی\u200cهای داشبورد'),
        ),
    ]
