# Generated by Django 6.0.5 on 2026-08-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0030_user_dashboard_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='username_prefix',
            field=models.CharField(blank=True, default='', help_text='حرف اول نام کاربری مالک — برای ساخت نام کاربری کارمندان (مثلاً: z)', max_length=5, verbose_name='پیشوند نام کاربری'),
        ),
    ]
