# Generated by Django 6.0.5 on 2026-08-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0031_restaurant_username_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='slug',
            field=models.CharField(db_index=True, default=1, help_text='آدرس رستوران — مثلاً: 1، 200، zfc-ali، hamid', max_length=50, unique=True, verbose_name='شناسه URL'),
            preserve_default=False,
        ),
    ]
