# Generated by Django 6.0.5 on 2026-08-09 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0035_add_service_tables'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='tenantservice',
            options={'ordering': ['service__order']},
        ),
        migrations.AddField(
            model_name='tenantservice',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ پایان'),
        ),
        migrations.AddField(
            model_name='tenantservice',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='service',
            name='default_price',
            field=models.BigIntegerField(default=0, help_text='قیمت پیش\u200cفرض ماهانه (تومان)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='tenantservice',
            name='price',
            field=models.BigIntegerField(default=0, help_text='قیمت ماهانه (تومان)'),
        ),
        migrations.AlterField(
            model_name='tenantservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_services', to='restaurant.service'),
        ),
        migrations.AlterField(
            model_name='tenantservice',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='restaurant.tenant'),
        ),
    ]
