# Generated by Django 6.0.5 on 2026-06-17 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_orderitem_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='readymaterial',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ready_materials', to='restaurant.category', verbose_name='دسته\u200cبندی'),
        ),
    ]
