# Generated by Django 6.0.5 on 2026-06-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_alter_semifinished_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='semifinished',
            name='current_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='موجودی فعلی (کیلو/لیتر/عدد)'),
        ),
    ]
