# Generated by Django 6.0.5 on 2026-06-20 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_semifinished_current_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='دلیل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('kitchen_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_logs', to='restaurant.kitchenproduct', verbose_name='محصول آشپزخانه')),
            ],
            options={
                'verbose_name': 'ضایعات',
                'verbose_name_plural': 'ضایعات',
                'ordering': ['-created_at'],
            },
        ),
    ]
