# Generated by Django 6.0.5 on 2026-06-21 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_wastelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayCloseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('action', models.CharField(choices=[('close', 'بستن روز'), ('reopen', 'باز کردن مجدد')], max_length=20, verbose_name='عملیات')),
                ('details', models.JSONField(default=dict, verbose_name='جزئیات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='day_logs', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'لاگ بستن روز',
                'verbose_name_plural': 'لاگ\u200cهای بستن روز',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DayCloseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='تاریخ')),
                ('total_sales', models.IntegerField(default=0, verbose_name='فروش کل')),
                ('total_cost', models.IntegerField(default=0, verbose_name='هزینه کل')),
                ('total_profit', models.IntegerField(default=0, verbose_name='سود خالص')),
                ('order_count', models.IntegerField(default=0, verbose_name='تعداد سفارش')),
                ('delivered_count', models.IntegerField(default=0, verbose_name='تحویل شده')),
                ('waste_count', models.IntegerField(default=0, verbose_name='تعداد ضایعات')),
                ('waste_value', models.IntegerField(default=0, verbose_name='ارزش ضایعات')),
                ('discount_total', models.IntegerField(default=0, verbose_name='کل تخفیف')),
                ('inventory_snapshot', models.JSONField(default=dict, verbose_name='عکس موجودی')),
                ('items_detail', models.JSONField(default=list, verbose_name='جزئیات آیتم\u200cها')),
                ('top_items', models.JSONField(default=list, verbose_name='پرفروش\u200cترین\u200cها')),
                ('closed_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان بستن')),
                ('closed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_reports', to=settings.AUTH_USER_MODEL, verbose_name='بسته شده توسط')),
            ],
            options={
                'verbose_name': 'گزارش بستن روز',
                'verbose_name_plural': 'گزارش\u200cهای بستن روز',
                'ordering': ['-date'],
            },
        ),
    ]
