# Generated by Django 6.0.5 on 2026-06-22 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_alter_daycloselog_details_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'سفارش', 'verbose_name_plural': 'سفارشات'},
        ),
        migrations.AddField(
            model_name='food',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='food',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='applicable_levels',
            field=models.ManyToManyField(blank=True, related_name='coupons', to='restaurant.membershiplevel', verbose_name='سطوح قابل استفاده'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='total_spending',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='مجموع خرید'),
        ),
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='restaurant.category'),
        ),
        migrations.AlterField(
            model_name='kitchendiscount',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان انقضا'),
        ),
        migrations.AlterField(
            model_name='kitchendiscount',
            name='max_quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='حداکثر تعداد'),
        ),
        migrations.AlterField(
            model_name='kitchendiscount',
            name='minimum_stock',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='حداقل موجودی'),
        ),
        migrations.AlterField(
            model_name='kitchendiscount',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='ساعت شروع'),
        ),
        migrations.AlterField(
            model_name='kitchendiscount',
            name='value',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='membershiplevel',
            name='min_spending',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='حداقل خرید'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('confirmed', 'تأیید شده'), ('preparing', 'در حال آماده\u200cسازی'), ('ready', 'آماده'), ('delivered', 'تحویل داده شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='label',
            field=models.CharField(blank=True, max_length=200, verbose_name='برچسب'),
        ),
        migrations.AlterField(
            model_name='semifinished',
            name='current_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='موجودی فعلی'),
        ),
    ]
