# Generated by Django 6.0.5 on 2026-06-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_alter_order_options_food_is_available_food_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayclosereport',
            name='date',
            field=models.DateField(verbose_name='تاریخ'),
        ),
    ]
