# Generated by Django 6.0.5 on 2026-07-02 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_alter_dayclosereport_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kitcheninventory',
            options={'ordering': ['-updated_at'], 'verbose_name': 'موجودی آشپزخانه', 'verbose_name_plural': 'موجودی\u200cهای آشپزخانه'},
        ),
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=True, verbose_name='تأیید مدیر'),
        ),
    ]
