# Generated by Django 6.0.5 on 2026-07-16 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0015_alter_user_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='نام')),
                ('unit', models.CharField(choices=[('kg', 'کیلوگرم'), ('g', 'گرم'), ('l', 'لیتر'), ('ml', 'میلی\u200cلیتر'), ('unit', 'عدد'), ('bunch', 'دسته'), ('pack', 'بسته')], max_length=10, verbose_name='واحد')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('category', models.CharField(choices=[('raw_material', 'ماده اولیه'), ('semi_finished', 'نیمه\u200cآماده'), ('ready_material', 'ماده آماده'), ('final_product', 'محصول نهایی')], db_index=True, max_length=20, verbose_name='دسته\u200cبندی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'دیکشنری آیتم',
                'verbose_name_plural': 'دیکشنری آیتم\u200cها',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='customerprofile',
            name='restaurant__phone_32787a_idx',
        ),
        migrations.AddField(
            model_name='capacityanalysis',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='restaurant.restaurant', verbose_name='رستوران'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='restaurant.restaurant', verbose_name='رستوران'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupon',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='restaurant.restaurant', verbose_name='رستوران'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customercoupon',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='restaurant.restaurant', verbose_name='رستوران'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='restaurant.restaurant', verbose_name='رستوران'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='daycloselog',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='restaurant.restaurant', verbose_name='رستوران'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dayclosereport',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='restaurant.restaurant', verbose_name='رستوران'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='restaurant.restaurant', verbose_name='رستوران'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryusagelog',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='restaurant.restaurant', verbose_name='رستوران'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kitchendiscount',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='restaurant.restaurant', verbose_name='رستوران'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kitcheninventory',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='restaurant.restaurant', verbose_name='رستوران'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kitchenproduct',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='restaurant.restaurant', verbose_name='رستوران'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loyaltynotification',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='restaurant.restaurant', verbose_name='رستوران'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loyaltytransaction',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='restaurant.restaurant', verbose_name='رستوران'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loyaltywallet',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='restaurant.restaurant', verbose_name='رستوران'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membershiplevel',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='restaurant.restaurant', verbose_name='رستوران'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='restaurant.restaurant', verbose_name='رستوران'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='restaurant.restaurant', verbose_name='رستوران'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='restaurant.restaurant', verbose_name='رستوران'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productionlog',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='restaurant.restaurant', verbose_name='رستوران'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productionplan',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='restaurant.restaurant', verbose_name='رستوران'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productionplanitem',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='restaurant.restaurant', verbose_name='رستوران'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='restaurant.restaurant', verbose_name='رستوران'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='restaurant.restaurant', verbose_name='رستوران'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='restaurant.restaurant', verbose_name='رستوران'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='readymaterial',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='restaurant.restaurant', verbose_name='رستوران'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='restaurant.restaurant', verbose_name='رستوران'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipesemifinished',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='restaurant.restaurant', verbose_name='رستوران'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referral',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='restaurant.restaurant', verbose_name='رستوران'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='restaurant.restaurant', verbose_name='رستوران'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reward',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='restaurant.restaurant', verbose_name='رستوران'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rewardredemption',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='restaurant.restaurant', verbose_name='رستوران'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='semifinished',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='restaurant.restaurant', verbose_name='رستوران'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='semifinishedingredient',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='restaurant.restaurant', verbose_name='رستوران'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='restaurant.restaurant', verbose_name='رستوران'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='restaurant.restaurant', verbose_name='رستوران'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='restaurant.restaurant', verbose_name='رستوران'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wastelog',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='restaurant.restaurant', verbose_name='رستوران'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='نام دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=30, verbose_name='کد کوپن'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='نام کوپن'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='شماره موبایل'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='referral_code',
            field=models.CharField(blank=True, max_length=12, verbose_name='کد دعوت'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='dayclosereport',
            name='discount_total',
            field=models.DecimalField(decimal_places=0, max_digits=14, verbose_name='کل تخفیف'),
        ),
        migrations.AlterField(
            model_name='dayclosereport',
            name='total_cost',
            field=models.DecimalField(decimal_places=0, max_digits=14, verbose_name='هزینه کل'),
        ),
        migrations.AlterField(
            model_name='dayclosereport',
            name='total_profit',
            field=models.DecimalField(decimal_places=0, max_digits=14, verbose_name='سود خالص'),
        ),
        migrations.AlterField(
            model_name='dayclosereport',
            name='total_sales',
            field=models.DecimalField(decimal_places=0, max_digits=14, verbose_name='فروش کل'),
        ),
        migrations.AlterField(
            model_name='dayclosereport',
            name='waste_value',
            field=models.DecimalField(decimal_places=0, max_digits=14, verbose_name='ارزش ضایعات'),
        ),
        migrations.AlterField(
            model_name='food',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='food',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='موجود'),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='نام غذا'),
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='restaurant.restaurant', verbose_name='رستوران'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kitchendiscount',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='نام تخفیف'),
        ),
        migrations.AlterField(
            model_name='kitchenproduct',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='kitchenproduct',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='نام محصول'),
        ),
        migrations.AlterField(
            model_name='loyaltynotification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='loyaltywallet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='membershiplevel',
            name='name',
            field=models.CharField(choices=[('bronze', 'برنز'), ('silver', 'نقره\u200cای'), ('gold', 'طلایی'), ('vip', 'VIP')], max_length=20, verbose_name='سطح'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('confirmed', 'تأیید شده'), ('preparing', 'در حال آماده\u200cسازی'), ('ready', 'آماده'), ('delivered', 'تحویل داده شده'), ('cancelled', 'لغو شده')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='productionbatch',
            name='notes',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='productionlog',
            name='details',
            field=models.TextField(blank=True, verbose_name='جزئیات'),
        ),
        migrations.AlterField(
            model_name='productionplan',
            name='notes',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='productionplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='supplier_name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='نام تأمین\u200cکننده'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت (تومان)'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='نام ماده اولیه'),
        ),
        migrations.AlterField(
            model_name='readymaterial',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='بارکد'),
        ),
        migrations.AlterField(
            model_name='readymaterial',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='نام ماده'),
        ),
        migrations.AlterField(
            model_name='readymaterial',
            name='purchase_price',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت خرید (تومان)'),
        ),
        migrations.AlterField(
            model_name='readymaterial',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='readymaterial',
            name='selling_price',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت فروش (تومان)'),
        ),
        migrations.AlterField(
            model_name='readymaterial',
            name='unit',
            field=models.CharField(choices=[('kg', 'کیلوگرم'), ('g', 'گرم'), ('l', 'لیتر'), ('ml', 'میلی\u200cلیتر'), ('unit', 'عدد'), ('bunch', 'دسته'), ('pack', 'بسته')], default='unit', max_length=10, verbose_name='واحد'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cost_per_serving',
            field=models.DecimalField(decimal_places=0, max_digits=14, verbose_name='هزینه هر سرو'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='restaurant.restaurant', verbose_name='رستوران'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='suggested_price',
            field=models.DecimalField(decimal_places=0, max_digits=14, verbose_name='قیمت پیشنهادی'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='total_cost',
            field=models.DecimalField(decimal_places=0, max_digits=14, verbose_name='هزینه کل'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='total_raw_material_cost',
            field=models.DecimalField(decimal_places=0, max_digits=14, verbose_name='هزینه مواد اولیه'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='total_semi_finished_cost',
            field=models.DecimalField(decimal_places=0, max_digits=14, verbose_name='هزینه مواد نیم\u200cآماده'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(choices=[('kg', 'کیلوگرم'), ('g', 'گرم'), ('l', 'لیتر'), ('ml', 'میلی\u200cلیتر'), ('unit', 'عدد'), ('bunch', 'دسته'), ('pack', 'بسته')], default='unit', max_length=10, verbose_name='واحد'),
        ),
        migrations.AlterField(
            model_name='recipesemifinished',
            name='unit',
            field=models.CharField(choices=[('kg', 'کیلوگرم'), ('g', 'گرم'), ('l', 'لیتر'), ('ml', 'میلی\u200cلیتر'), ('unit', 'عدد'), ('bunch', 'دسته'), ('pack', 'بسته')], default='unit', max_length=10, verbose_name='واحد'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='customer_name',
            field=models.CharField(max_length=200, verbose_name='نام مشتری'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='تلفن'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='نام رستوران'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='نام جایزه'),
        ),
        migrations.AlterField(
            model_name='semifinished',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='semifinished',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='نام ماده نیم\u200cآماده'),
        ),
        migrations.AlterField(
            model_name='semifinished',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='نام شرکت'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'مالک'), ('manager', 'مدیر'), ('cashier', 'صندوقدار'), ('kitchen', 'آشپزخانه'), ('warehouse', 'انباردار'), ('customer', 'مشتری')], db_index=True, default='customer', max_length=20, verbose_name='نقش'),
        ),
        migrations.AlterField(
            model_name='wastelog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterUniqueTogether(
            name='coupon',
            unique_together={('restaurant', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='membershiplevel',
            unique_together={('restaurant', 'name')},
        ),
        migrations.AddIndex(
            model_name='customerprofile',
            index=models.Index(fields=['restaurant', 'phone'], name='restaurant__restaur_dc4b2b_idx'),
        ),
        migrations.AddIndex(
            model_name='customerprofile',
            index=models.Index(fields=['membership_level', '-total_spending'], name='restaurant__members_fee928_idx'),
        ),
        migrations.AddIndex(
            model_name='dayclosereport',
            index=models.Index(fields=['restaurant', '-date'], name='restaurant__restaur_11e3c2_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltynotification',
            index=models.Index(fields=['customer', 'is_read', '-created_at'], name='restaurant__custome_03ec58_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='restaurant__status_be8448_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['table', '-created_at'], name='restaurant__table_i_17e9bd_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'food'], name='restaurant__order_i_b2bdb6_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['-date'], name='restaurant__date_70bbd4_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['supplier_name'], name='restaurant__supplie_061cda_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['date', 'time'], name='restaurant__date_9c0bc5_idx'),
        ),
        migrations.AddField(
            model_name='itemdictionary',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='restaurant.restaurant', verbose_name='رستوران'),
        ),
        migrations.AlterUniqueTogether(
            name='itemdictionary',
            unique_together={('restaurant', 'name', 'category')},
        ),
    ]
