# Generated by Django 6.0.5 on 2026-07-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0016_itemdictionary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayclosereport',
            name='discount_total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='کل تخفیف'),
        ),
        migrations.AlterField(
            model_name='dayclosereport',
            name='total_cost',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='هزینه کل'),
        ),
        migrations.AlterField(
            model_name='dayclosereport',
            name='total_profit',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='سود خالص'),
        ),
        migrations.AlterField(
            model_name='dayclosereport',
            name='total_sales',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='فروش کل'),
        ),
        migrations.AlterField(
            model_name='dayclosereport',
            name='waste_value',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='ارزش ضایعات'),
        ),
        migrations.AlterField(
            model_name='food',
            name='final_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='قیمت نهایی'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cost_per_serving',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='هزینه هر سرو'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='suggested_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='قیمت پیشنهادی'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='total_cost',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='هزینه کل'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='total_raw_material_cost',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='هزینه مواد اولیه'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='total_semi_finished_cost',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='هزینه مواد نیم\u200cآماده'),
        ),
    ]
